测试打包

diff --git a/.github/workflows/release-no-one.yml b/.github/workflows/release-no-one.yml
--- a/.github/workflows/release-no-one.yml
+++ b/.github/workflows/release-no-one.yml
@@ -11,6 +11,10 @@ on:
         description: 'Branch to checkout from private repository (e.g., dev, main)'
         required: true
         default: 'dev'
+      build_no_one:
+        description: 'Build for NO ONE (true/false)'
+        required: false
+        default: 'false'
   push:
     tags:
       - v*.*.*
@@ -82,28 +86,6 @@ jobs:
       - name: Install Dependencies
         run: npm install --legacy-peer-deps # Added --legacy-peer-deps based on common Electron/Vite project needs, remove if not necessary
 
-      - name: Replace package.json values for stealth build
-        shell: bash
-        run: |
-          # Use Node.js to modify package.json
-          node -e "
-          const fs = require('fs');
-          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
-          pkg.name = 'Desktophelper';
-          // Replace productName
-          pkg.build.productName = 'Desktophelper';
-          
-          // Replace Mac icon
-          pkg.build.mac.icon = 'assets/icons/mac/blank.icns';
-          
-          // Replace Windows icon  
-          pkg.build.win.icon = 'assets/icons/win/blank.ico';
-          
-          // Write the modified package.json
-          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
-          console.log('✅ package.json modified for stealth build');
-          "
-
       - name: Build Mac
         if: matrix.os == 'macos-latest'
         run: npm run package-mac
@@ -114,11 +96,11 @@ jobs:
       - name: Submit app for notarization
         if: matrix.os == 'macos-latest'
         run: |
-          SUBMISSION_OUTPUT_ARM64=$(xcrun notarytool submit --force release/Desktophelper-*-arm64.dmg --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID  }}")
+          SUBMISSION_OUTPUT_ARM64=$(xcrun notarytool submit --force release/GankInterview-*-arm64.dmg --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID  }}")
           echo "$SUBMISSION_OUTPUT_ARM64"
           SUBMISSION_ID_ARM64=$(echo "$SUBMISSION_OUTPUT_ARM64" | grep "id:" | head -1 | awk '{print $2}')
           echo "SUBMISSION_ID_ARM64=$SUBMISSION_ID_ARM64" >> $GITHUB_ENV
-          SUBMISSION_OUTPUT_X64=$(xcrun notarytool submit --force release/Desktophelper-*-x64.dmg --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID  }}")
+          SUBMISSION_OUTPUT_X64=$(xcrun notarytool submit --force release/GankInterview-*-x64.dmg --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID  }}")
           echo "$SUBMISSION_OUTPUT_X64"
           SUBMISSION_ID_X64=$(echo "$SUBMISSION_OUTPUT_X64" | grep "id:" | head -1 | awk '{print $2}')
           echo "SUBMISSION_ID_X64=$SUBMISSION_ID_X64" >> $GITHUB_ENV
@@ -171,6 +153,105 @@ jobs:
           done
 
       - name: Build Windows
+        if: matrix.os == 'windows-latest'
+        run: npm run package-win
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+
+      - name: Replace package.json values for stealth build
+        if: github.event.inputs.build_no_one == 'true'
+        shell: bash
+        run: |
+          # Use Node.js to modify package.json
+          node -e "
+          const fs = require('fs');
+          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
+          pkg.name = 'Desktophelper';
+          // Replace productName
+          pkg.build.productName = 'Desktophelper';
+          
+          // Replace Mac icon
+          pkg.build.mac.icon = 'assets/icons/mac/blank.icns';
+          
+          // Replace Windows icon  
+          pkg.build.win.icon = 'assets/icons/win/blank.ico';
+          
+          // Write the modified package.json
+          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
+          console.log('✅ package.json modified for stealth build');
+          "
+
+      - name: Build Mac
+        if: github.event.inputs.build_no_one == 'true'
+        if: matrix.os == 'macos-latest'
+        run: npm run package-mac
+        env:
+          CSC_LINK: ${{ secrets.CSC_LINK }}
+          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Submit app for notarization
+        if: matrix.os == 'macos-latest'
+        run: |
+          SUBMISSION_OUTPUT_ARM64=$(xcrun notarytool submit --force release/Desktophelper-*-arm64.dmg --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID  }}")
+          echo "$SUBMISSION_OUTPUT_ARM64"
+          SUBMISSION_ID_ARM64=$(echo "$SUBMISSION_OUTPUT_ARM64" | grep "id:" | head -1 | awk '{print $2}')
+          echo "SUBMISSION_ID_ARM64=$SUBMISSION_ID_ARM64" >> $GITHUB_ENV
+          SUBMISSION_OUTPUT_X64=$(xcrun notarytool submit --force release/Desktophelper-*-x64.dmg --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID  }}")
+          echo "$SUBMISSION_OUTPUT_X64"
+          SUBMISSION_ID_X64=$(echo "$SUBMISSION_OUTPUT_X64" | grep "id:" | head -1 | awk '{print $2}')
+          echo "SUBMISSION_ID_X64=$SUBMISSION_ID_X64" >> $GITHUB_ENV
+      
+      - name: Check notarization status
+        if: github.event.inputs.build_no_one == 'true'
+        if: matrix.os == 'macos-latest'
+        run: |
+          MAX_ATTEMPTS=10
+          ATTEMPT=1
+          for i in $(seq 1 $MAX_ATTEMPTS); do
+            STATUS_OUTPUT_ARM64=$(xcrun notarytool info $SUBMISSION_ID_ARM64 --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID  }}")
+            echo "$STATUS_OUTPUT_ARM64"
+            STATUS_ARM64=$(echo "$STATUS_OUTPUT_ARM64" | grep "status:" |  sed 's/status: //'| xargs)
+            if [ "$STATUS_ARM64" = "Accepted" ]; then
+              echo "Notarization succeeded!"
+              break
+            elif [ "$STATUS_ARM64" = "In Progress" ]; then
+              echo "Notarization in progress, retrying in 600 seconds..."
+              sleep 600
+              ATTEMPT=$((ATTEMPT + 1))
+            else
+              echo "Notarization failed with status: $STATUS_ARM64"
+              exit 1
+            fi
+            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
+              echo "Max attempts reached, notarization still in progress."
+              exit 1
+            fi
+          done
+          ATTEMPT=1
+          for i in $(seq 1 $MAX_ATTEMPTS); do
+            STATUS_OUTPUT_X64=$(xcrun notarytool info $SUBMISSION_ID_X64 --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APPLE_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID  }}")
+            echo "$STATUS_OUTPUT_X64"
+            STATUS_X64=$(echo "$STATUS_OUTPUT_X64" | grep "status:" |  sed 's/status: //'| xargs)
+            if [ "$STATUS_X64" = "Accepted" ]; then
+              echo "Notarization succeeded!"
+              break
+            elif [ "$STATUS_X64" = "In Progress" ]; then
+              echo "Notarization in progress, retrying in 600 seconds..."
+              sleep 600
+              ATTEMPT=$((ATTEMPT + 1))
+            else
+              echo "Notarization failed with status: $STATUS_X64"
+              exit 1
+            fi
+            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
+              echo "Max attempts reached, notarization still in progress."
+              exit 1
+            fi
+          done
+
+      - name: Build Windows
+        if: github.event.inputs.build_no_one == 'true'
         if: matrix.os == 'windows-latest'
         run: npm run package-win
         env:
